"""
INI configuration loader for forensicnova_analyzer.

Mirrors the architectural choice already adopted in `app/config.py`:
  - stdlib `configparser` (zero external dependencies)
  - immutable dataclass as a typed configuration container
  - INI file at /etc/forensicnova/forensicnova-analyzer.conf

INI sections handled:

    [forensicnova_analyzer] runtime / bind / paths
    [keystone]              identity discovery (auth_url, region, role)
    [keystone_authtoken]    service credentials for keystonemiddleware
                            (consumed when authenticated endpoints become
                            active in Stage E2+)
    [swift]                 object storage container name
    [forensics]             DFIR project context (project name, dfir user)

Naming convention is intentionally aligned with `app/config.py` so the
two backends remain operationally familiar and the configuration model
stays predictable across the project.

Sensitive values:
  - keystone_authtoken_password: read from the INI file (mode 640
    stack:stack) and may be overridden by env var
    FORENSICNOVA_KEYSTONE_AUTHTOKEN_PASSWORD if set.
  - The dfir-tester password used by `forensicnova_analyzer/swift.py`
    is NOT loaded here. It is read from env var FORENSICNOVA_DFIR_PASSWORD
    at call time (injected by the systemd unit), so it never lives on
    disk in the analyzer's config file.

The file is generated by the DevStack plugin in the `post-config` phase
from the sample in etc/forensicnova-analyzer.conf.sample. Overrides can
be set in local.conf via FORENSICNOVA_ANALYZER_* and FORENSICNOVA_*
variables.
"""
from __future__ import annotations

import configparser
import os
from dataclasses import dataclass


@dataclass(frozen=True)
class AnalyzerConfig:
    """Immutable analyzer configuration.

    `frozen=True` prevents post-construction mutations, avoiding bugs
    caused by accidental mutation during request handling.
    """

    # [forensicnova_analyzer] — runtime / bind / paths
    bind_host: str
    bind_port: int
    log_file: str
    log_level: str
    work_dir: str
    jobs_dir: str

    # [keystone] — identity discovery
    keystone_auth_url: str
    keystone_region: str
    keystone_forensic_role: str

    # [keystone_authtoken] — service credentials for keystonemiddleware
    keystone_authtoken_username: str
    keystone_authtoken_password: str
    keystone_authtoken_project: str

    # [swift] — object storage
    swift_container: str

    # [forensics] — DFIR project context
    forensics_project: str
    forensics_dfir_user: str


def load_config(path: str) -> AnalyzerConfig:
    """Read the INI file and return an AnalyzerConfig.

    Raises FileNotFoundError if the file does not exist, KeyError if
    the mandatory [forensicnova_analyzer] section is missing, ValueError
    if types are wrong.

    The four extension sections ([keystone], [keystone_authtoken],
    [swift], [forensics]) are optional in this loader: if absent, sane
    defaults aligned with the project's DevStack deployment are used.
    The DevStack plugin always writes all of them at post-config time,
    so the optional-section path is exercised only in unit tests or
    hand-edited environments.
    """
    parser = configparser.ConfigParser()
    files_read = parser.read(path)
    if not files_read:
        raise FileNotFoundError(f"config file not found: {path}")

    section_name = "forensicnova_analyzer"
    if section_name not in parser:
        raise KeyError(
            f"section [{section_name}] missing from config file {path}"
        )

    main = parser[section_name]
    bind_host = main.get("bind_host", "0.0.0.0")
    bind_port = main.getint("bind_port", 5235)
    log_file = main.get("log_file", "/var/log/forensicnova/analyzer.log")
    log_level = main.get("log_level", "INFO")
    work_dir = main.get("work_dir", "/var/lib/forensicnova-analyzer")
    jobs_dir = main.get("jobs_dir", "/var/lib/forensicnova-analyzer/jobs")

    # [keystone]
    if parser.has_section("keystone"):
        ks = parser["keystone"]
        keystone_auth_url = ks.get("auth_url", "")
        keystone_region = ks.get("region_name", "RegionOne")
        keystone_forensic_role = ks.get("forensic_role", "forensic_analyst")
    else:
        keystone_auth_url = ""
        keystone_region = "RegionOne"
        keystone_forensic_role = "forensic_analyst"

    # [keystone_authtoken]
    if parser.has_section("keystone_authtoken"):
        kt = parser["keystone_authtoken"]
        keystone_authtoken_username = kt.get("username", "admin")
        keystone_authtoken_password = kt.get("password", "")
        keystone_authtoken_project = kt.get("project_name", "admin")
    else:
        keystone_authtoken_username = "admin"
        keystone_authtoken_password = ""
        keystone_authtoken_project = "admin"

    # Allow env var override of the keystonemiddleware password — same
    # pattern as app/config.py so production deployments can avoid
    # storing it in a file on disk.
    env_pwd = os.environ.get("FORENSICNOVA_KEYSTONE_AUTHTOKEN_PASSWORD", "")
    if env_pwd:
        keystone_authtoken_password = env_pwd

    # [swift]
    if parser.has_section("swift"):
        swift_container = parser["swift"].get("container", "forensics")
    else:
        swift_container = "forensics"

    # [forensics]
    if parser.has_section("forensics"):
        fr = parser["forensics"]
        forensics_project = fr.get("project", "forensics")
        forensics_dfir_user = fr.get("dfir_user", "dfir-tester")
    else:
        forensics_project = "forensics"
        forensics_dfir_user = "dfir-tester"

    return AnalyzerConfig(
        bind_host=bind_host,
        bind_port=bind_port,
        log_file=log_file,
        log_level=log_level,
        work_dir=work_dir,
        jobs_dir=jobs_dir,
        keystone_auth_url=keystone_auth_url,
        keystone_region=keystone_region,
        keystone_forensic_role=keystone_forensic_role,
        keystone_authtoken_username=keystone_authtoken_username,
        keystone_authtoken_password=keystone_authtoken_password,
        keystone_authtoken_project=keystone_authtoken_project,
        swift_container=swift_container,
        forensics_project=forensics_project,
        forensics_dfir_user=forensics_dfir_user,
    )
