"""
INI configuration loader for forensicnova_analyzer.

Mirrors the architectural choice already adopted in `app/config.py`:
  - stdlib `configparser` (zero external dependencies)
  - immutable dataclass as a typed configuration container
  - INI file at /etc/forensicnova/forensicnova-analyzer.conf

Expected section in the INI file:

    [forensicnova_analyzer]
    bind_host = 0.0.0.0
    bind_port = 5235
    log_file = /var/log/forensicnova/analyzer.log
    log_level = INFO
    work_dir = /var/lib/forensicnova-analyzer
    jobs_dir = /var/lib/forensicnova-analyzer/jobs

The file is generated by the DevStack plugin in the `post-config` phase
from the sample in etc/forensicnova-analyzer.conf.sample. Overrides can
be set in local.conf via FORENSICNOVA_ANALYZER_* variables.
"""

import configparser
from dataclasses import dataclass


@dataclass(frozen=True)
class AnalyzerConfig:
    """Immutable analyzer configuration.

    `frozen=True` prevents post-construction mutations, avoiding bugs
    caused by accidental mutation during request handling.
    """

    bind_host: str
    bind_port: int
    log_file: str
    log_level: str
    work_dir: str
    jobs_dir: str


def load_config(path: str) -> AnalyzerConfig:
    """Read the INI file and return an AnalyzerConfig.

    Raises FileNotFoundError if the file does not exist, KeyError if
    the expected section is missing, ValueError if types are wrong.
    """
    parser = configparser.ConfigParser()
    files_read = parser.read(path)
    if not files_read:
        raise FileNotFoundError(f"config file not found: {path}")

    section_name = "forensicnova_analyzer"
    if section_name not in parser:
        raise KeyError(
            f"section [{section_name}] missing from config file {path}"
        )

    section = parser[section_name]

    return AnalyzerConfig(
        bind_host=section.get("bind_host", "0.0.0.0"),
        bind_port=section.getint("bind_port", 5235),
        log_file=section.get(
            "log_file",
            "/var/log/forensicnova/analyzer.log",
        ),
        log_level=section.get("log_level", "INFO"),
        work_dir=section.get(
            "work_dir",
            "/var/lib/forensicnova-analyzer",
        ),
        jobs_dir=section.get(
            "jobs_dir",
            "/var/lib/forensicnova-analyzer/jobs",
        ),
    )
