#!/usr/bin/env bash
# ForensicNova DevStack plugin
# https://github.com/numdav/forensicnova
#
# Lifecycle phases wired in this file:
#   stack pre-install   -> preinstall_forensicnova  (system packages)
#   stack install       -> install_forensicnova     (python venv + pip deps)
#   stack post-config   -> configure_forensicnova   (keystone, swift, fs, conf)
#   stack extra         -> init_forensicnova        (FASE 3: Flask service)
#   unstack             -> stop_forensicnova
#   clean               -> cleanup_forensicnova
#
# Docs: https://docs.openstack.org/devstack/latest/plugins.html

# Resolve plugin dir and (re-)source settings defensively.
FORENSICNOVA_PLUGIN_DIR=$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")
# shellcheck disable=SC1091
source "${FORENSICNOVA_PLUGIN_DIR}/settings"

# =============================================================================
# Logging helpers
# =============================================================================

forensicnova_marker() {
    # Single-line greppable marker ("[ForensicNova][<phase>] marker")
    local phase="$1"
    local msg="${2:-marker}"
    echo "[ForensicNova][${phase}] ${msg}"
}

forensicnova_log() {
    local phase="$1"; shift
    echo "[ForensicNova][${phase}] $*"
}

# =============================================================================
# Idempotent building blocks
# =============================================================================

# Create host-side directories with correct ownership and permissions.
forensicnova_ensure_dirs() {
    forensicnova_log "post-config" "ensuring runtime directories"
    local d
    for d in "$FORENSICNOVA_WORK_DIR" "$FORENSICNOVA_LOG_DIR" "$FORENSICNOVA_CONF_DIR"; do
        sudo mkdir -p "$d"
        sudo chown -R "$STACK_USER:$STACK_USER" "$d"
        sudo chmod 750 "$d"
    done
}

# Keystone identity artifacts: role + project + user + role assignments.
# Uses DevStack's native idempotent helpers (from lib/keystone).
forensicnova_ensure_identity() {
    forensicnova_log "post-config" "ensuring Keystone identity artifacts"

    # Custom role for forensic analysts
    get_or_create_role "$FORENSICNOVA_ROLE"

    # Dedicated project for DFIR artifacts
    get_or_create_project "$FORENSICNOVA_PROJECT" default \
        "$FORENSICNOVA_PROJECT_DESCRIPTION"

    # Test user (password, domain)
    get_or_create_user "$FORENSICNOVA_DFIR_USER" \
        "$FORENSICNOVA_DFIR_PASSWORD" default

    # Assignments: custom role for our plugin policy + member for baseline ops
    get_or_add_user_project_role "$FORENSICNOVA_ROLE" \
        "$FORENSICNOVA_DFIR_USER" "$FORENSICNOVA_PROJECT"
    get_or_add_user_project_role "member" \
        "$FORENSICNOVA_DFIR_USER" "$FORENSICNOVA_PROJECT"
}

# Swift container in the 'forensics' project (NOT admin).
# We scope the call via a subshell with overridden OS_* variables so we don't
# pollute the admin environment that DevStack relies on for the rest of setup.
forensicnova_ensure_container() {
    forensicnova_log "post-config" \
        "ensuring Swift container '$FORENSICNOVA_SWIFT_CONTAINER' in project '$FORENSICNOVA_PROJECT'"
    (
        export OS_USERNAME="$FORENSICNOVA_DFIR_USER"
        export OS_PASSWORD="$FORENSICNOVA_DFIR_PASSWORD"
        export OS_PROJECT_NAME="$FORENSICNOVA_PROJECT"
        export OS_USER_DOMAIN_ID=default
        export OS_PROJECT_DOMAIN_ID=default
        # OS_AUTH_URL, OS_IDENTITY_API_VERSION, OS_REGION_NAME are inherited
        # from the admin openrc already sourced by DevStack.
        openstack container show "$FORENSICNOVA_SWIFT_CONTAINER" >/dev/null 2>&1 \
            || openstack container create "$FORENSICNOVA_SWIFT_CONTAINER" >/dev/null
    )
}

# Write /etc/forensicnova/forensicnova.conf (regenerated every stack.sh run).
forensicnova_write_config() {
    forensicnova_log "post-config" "writing $FORENSICNOVA_CONF_FILE"
    sudo tee "$FORENSICNOVA_CONF_FILE" >/dev/null <<EOF
# ForensicNova plugin configuration
# Generated by devstack/plugin.sh — regenerated on every stack.sh run.
# DO NOT EDIT — changes will be overwritten.

[DEFAULT]
bind_host = ${FORENSICNOVA_BIND_HOST}
bind_port = ${FORENSICNOVA_PORT}
work_dir = ${FORENSICNOVA_WORK_DIR}
log_dir = ${FORENSICNOVA_LOG_DIR}

[keystone]
auth_url = ${OS_AUTH_URL}
region_name = ${OS_REGION_NAME}
forensic_role = ${FORENSICNOVA_ROLE}

[swift]
container = ${FORENSICNOVA_SWIFT_CONTAINER}
# Swift endpoint is discovered via the Keystone service catalog at runtime.

[forensics]
project = ${FORENSICNOVA_PROJECT}
dfir_user = ${FORENSICNOVA_DFIR_USER}

[libvirt]
uri = qemu:///system
EOF
    sudo chown "$STACK_USER:$STACK_USER" "$FORENSICNOVA_CONF_FILE"
    sudo chmod 640 "$FORENSICNOVA_CONF_FILE"
}

# Regenerate /opt/stack/devstack/openrc-dfir for manual testing.
forensicnova_write_openrc() {
    forensicnova_log "post-config" "writing $FORENSICNOVA_OPENRC"
    cat > "$FORENSICNOVA_OPENRC" <<EOF
#!/usr/bin/env bash
# ForensicNova — openrc for ${FORENSICNOVA_DFIR_USER}
# Generated by devstack/plugin.sh. Do not edit manually.
export OS_AUTH_URL=${OS_AUTH_URL}
export OS_USERNAME=${FORENSICNOVA_DFIR_USER}
export OS_PASSWORD='${FORENSICNOVA_DFIR_PASSWORD}'
export OS_PROJECT_NAME=${FORENSICNOVA_PROJECT}
export OS_PROJECT_DOMAIN_ID=default
export OS_USER_DOMAIN_ID=default
export OS_IDENTITY_API_VERSION=3
export OS_AUTH_TYPE=password
export OS_REGION_NAME=${OS_REGION_NAME}
EOF
    chmod 600 "$FORENSICNOVA_OPENRC"
}

# Create dedicated virtualenv and install Python dependencies.
forensicnova_install_python_deps() {
    forensicnova_log "install" \
        "creating venv and installing Python deps in $FORENSICNOVA_DIR/.venv"
    python3 -m venv "$FORENSICNOVA_DIR/.venv"
    local venv_pip="$FORENSICNOVA_DIR/.venv/bin/pip"
    "$venv_pip" install --quiet --disable-pip-version-check --upgrade pip setuptools wheel
    "$venv_pip" install --quiet --disable-pip-version-check \
        Flask \
        reportlab \
        python-swiftclient \
        python-keystoneclient \
        python-novaclient \
        keystonemiddleware \
        requests
}

# =============================================================================
# Phase functions
# =============================================================================

preinstall_forensicnova() {
    forensicnova_marker "pre-install"
    # virsh sanity check (non-fatal; all-in-one DevStack has it via n-cpu)
    if ! command -v virsh >/dev/null 2>&1; then
        forensicnova_log "pre-install" \
            "WARNING: virsh not found — memory acquisition requires libvirt on the compute node"
    else
        forensicnova_log "pre-install" "virsh available: $(command -v virsh)"
    fi
    # python3-venv is required for the dedicated virtualenv created in 'install'
    if ! dpkg -s python3-venv >/dev/null 2>&1; then
        forensicnova_log "pre-install" "installing python3-venv"
        sudo apt-get install -y python3-venv
    fi
}

install_forensicnova() {
    forensicnova_marker "install"
    forensicnova_install_python_deps
}

configure_forensicnova() {
    forensicnova_marker "post-config"
# Controllo di sicurezza credenziali
    if [[ -z "$FORENSICNOVA_DFIR_PASSWORD" ]]; then
        forensicnova_log "post-config" "ERROR: FORENSICNOVA_DFIR_PASSWORD is unset. Set it in local.conf."
        return 1
    fi
    forensicnova_ensure_dirs
    forensicnova_write_config
    forensicnova_write_openrc
    forensicnova_log "post-config" "configuration completed successfully"
}

init_forensicnova() {
    forensicnova_marker "extra"
    forensicnova_ensure_identity
    forensicnova_ensure_container
    forensicnova_log "extra" "TODO FASE 3: register Flask service (devstack@forensicnova)"
}

stop_forensicnova() {
    forensicnova_marker "unstack" "stop (FASE 2b: no long-running service yet)"
}

cleanup_forensicnova() {
    forensicnova_marker "clean"
    sudo rm -rf "$FORENSICNOVA_WORK_DIR" "$FORENSICNOVA_LOG_DIR" "$FORENSICNOVA_CONF_DIR"
    rm -f "$FORENSICNOVA_OPENRC"
    rm -rf "$FORENSICNOVA_DIR/.venv"
}

# =============================================================================
# Dispatcher — DevStack invokes this script with positional args
# =============================================================================

if [[ "$1" == "stack" ]]; then
    case "$2" in
        pre-install)  preinstall_forensicnova ;;
        install)      install_forensicnova ;;
        post-config)  configure_forensicnova ;;
        extra)        init_forensicnova ;;
        *)            : ;;  # test-config and others: no-op
    esac
elif [[ "$1" == "unstack" ]]; then
    stop_forensicnova
elif [[ "$1" == "clean" ]]; then
    cleanup_forensicnova
fi