"""ForensicNova configuration loader.

Reads the INI file written by devstack/plugin.sh at stack time
(default path: /etc/forensicnova/forensicnova.conf) and exposes
a Config dataclass consumed by the Flask application factory.

INI sections handled:
    [DEFAULT]            runtime / bind
    [keystone]           identity discovery (auth_url, region, role)
    [keystone_authtoken] service credentials for keystonemiddleware (FASE 4)
    [swift]              object storage container name
    [forensics]          DFIR project context
    [libvirt]            hypervisor connection URI

Sensitive values:
  - keystone_authtoken_password: read from the INI file (mode 640 stack:stack)
    OR overridden by the FORENSICNOVA_KEYSTONE_AUTHTOKEN_PASSWORD env var if
    set.  This lets the systemd unit pass it without persisting on disk.

Derived paths:
  - secret_key_path: always ``{work_dir}/secret_key``.  Hardcoded by convention
    (not configurable via INI) to keep operator mental model simple: one
    path, kept in sync with work_dir.  Generated by plugin.sh post-config.
"""
from __future__ import annotations

import configparser
import os
from dataclasses import dataclass
from typing import Optional

DEFAULT_CONFIG_PATH = "/etc/forensicnova/forensicnova.conf"
DEFAULT_WORK_DIR = "/var/lib/forensicnova"


@dataclass
class Config:
    """Typed view of forensicnova.conf."""

    # [DEFAULT] — runtime / bind
    bind_host: str = "0.0.0.0"
    bind_port: int = 5234
    work_dir: str = DEFAULT_WORK_DIR
    log_dir: str = "/var/log/forensicnova"

    # [keystone] — identity discovery
    keystone_auth_url: str = ""
    keystone_region: str = "RegionOne"
    keystone_forensic_role: str = "forensic_analyst"

    # [keystone_authtoken] — service credentials for keystonemiddleware
    # The middleware uses these to authenticate against Keystone in order
    # to validate the user-supplied X-Auth-Token on each request.
    # By convention we use the admin user (sufficient privilege to validate
    # arbitrary tokens; for production a dedicated 'service' user with the
    # 'service' role on the 'service' project would be preferable).
    keystone_authtoken_username: str = "admin"
    keystone_authtoken_password: str = ""
    keystone_authtoken_project:  str = "admin"

    # [swift] — object storage container
    swift_container: str = "forensics"

    # [forensics] — DFIR project context
    forensics_project: str = "forensics"
    forensics_dfir_user: str = "dfir-tester"

    # [libvirt] — hypervisor connection
    libvirt_uri: str = "qemu:///system"

    # Flask — session signing key path (derived from work_dir in load_config)
    secret_key_path: str = f"{DEFAULT_WORK_DIR}/secret_key"

    # Bookkeeping
    config_path: str = DEFAULT_CONFIG_PATH


def load_config(path: Optional[str] = None) -> Config:
    """Load ForensicNova config from an INI file.

    Resolution order for the file path:
      1. Explicit ``path`` argument (used in tests).
      2. FORENSICNOVA_CONFIG environment variable.
      3. DEFAULT_CONFIG_PATH (production / DevStack).

    The keystone_authtoken_password is additionally overridable via the
    FORENSICNOVA_KEYSTONE_AUTHTOKEN_PASSWORD environment variable, which
    the systemd unit injects at process start.
    """
    cfg_path = path or os.environ.get("FORENSICNOVA_CONFIG", DEFAULT_CONFIG_PATH)

    cp = configparser.ConfigParser()
    cp.optionxform = str  # preserve key case
    read_files = cp.read(cfg_path)

    cfg = Config(config_path=cfg_path)

    if read_files:
        cfg.bind_host = cp.get("DEFAULT", "bind_host", fallback=cfg.bind_host)
        cfg.bind_port = cp.getint("DEFAULT", "bind_port", fallback=cfg.bind_port)
        cfg.work_dir  = cp.get("DEFAULT", "work_dir",  fallback=cfg.work_dir)
        cfg.log_dir   = cp.get("DEFAULT", "log_dir",   fallback=cfg.log_dir)

    if cp.has_section("keystone"):
        cfg.keystone_auth_url = cp.get(
            "keystone", "auth_url", fallback=cfg.keystone_auth_url
        )
        cfg.keystone_region = cp.get(
            "keystone", "region_name", fallback=cfg.keystone_region
        )
        cfg.keystone_forensic_role = cp.get(
            "keystone", "forensic_role", fallback=cfg.keystone_forensic_role
        )

    if cp.has_section("keystone_authtoken"):
        cfg.keystone_authtoken_username = cp.get(
            "keystone_authtoken", "username",
            fallback=cfg.keystone_authtoken_username,
        )
        cfg.keystone_authtoken_password = cp.get(
            "keystone_authtoken", "password",
            fallback=cfg.keystone_authtoken_password,
        )
        cfg.keystone_authtoken_project = cp.get(
            "keystone_authtoken", "project_name",
            fallback=cfg.keystone_authtoken_project,
        )

    # Env var overrides for sensitive values (preferred path in production).
    env_pwd = os.environ.get("FORENSICNOVA_KEYSTONE_AUTHTOKEN_PASSWORD", "")
    if env_pwd:
        cfg.keystone_authtoken_password = env_pwd

    if cp.has_section("swift"):
        cfg.swift_container = cp.get(
            "swift", "container", fallback=cfg.swift_container
        )

    if cp.has_section("forensics"):
        cfg.forensics_project = cp.get(
            "forensics", "project", fallback=cfg.forensics_project
        )
        cfg.forensics_dfir_user = cp.get(
            "forensics", "dfir_user", fallback=cfg.forensics_dfir_user
        )

    if cp.has_section("libvirt"):
        cfg.libvirt_uri = cp.get("libvirt", "uri", fallback=cfg.libvirt_uri)

    # Derived paths — kept in sync with work_dir.  Must come AFTER the
    # [DEFAULT] block parsing, because work_dir may have been overridden.
    cfg.secret_key_path = os.path.join(cfg.work_dir, "secret_key")

    return cfg
