"""ForensicNova — hypervisor-level RAM acquisition via libvirt.

Implements Scenario A+ ("hypervisor-local staging"):
  1. Connect to libvirt on the local compute node (qemu:///system).
  2. Resolve the Nova instance UUID to a libvirt domain object.
  3. Pre-check available disk space against the domain's declared max RAM.
  4. Invoke coreDumpWithFormat() — libvirt pauses QEMU briefly, reads guest
     RAM at hypervisor level, writes a raw file.  The guest OS is never
     written to and remains unaware of the acquisition.
  5. The resulting .raw file is compatible with Volatility 3 out of the box.

Post-dump ownership fix:
  libvirtd writes the dump file as root:root (by design of the QEMU driver
  running as a privileged daemon).  The rest of the pipeline (hasher,
  Swift uploader, secure_delete) runs as 'stack' and would otherwise fail
  with PermissionError.  We chown the file back to stack:stack via sudo
  immediately after the dump.  'stack' has NOPASSWD sudo in DevStack, so
  no interactive prompt is ever produced.

Forensic soundness guarantees provided by THIS module:
  - Zero writes to the guest filesystem (libvirt reads via /proc/<qemu>/mem).
  - Dump written to a dedicated per-acquisition directory owned by stack:stack,
    mode 700, under WORK_DIR/acquisitions/<acquisition_id>/.
  - Chain-of-custody events emitted at each meaningful step via the optional
    log_event callback (decoupled from the CoC module, same pattern as hasher).

Guarantees provided by the CALLER (app/api/v1.py):
  - Hash computation (hasher.py) before upload.
  - Swift upload + etag verification (swift_client.py).
  - secure_delete() called only after upload is confirmed.

secure_delete() is defined here because it is the bookend of the acquisition:
the temporary file on the hypervisor must be destroyed after the evidence is
safely on Swift, and the destroy logic belongs next to the create logic.

Dependencies:
  - libvirt-python  (pip install libvirt-python, already added to venv)
  - shred           (coreutils, always present on Ubuntu)
  - sudo NOPASSWD   (DevStack requirement for user 'stack')
"""
from __future__ import annotations

import logging
import os
import shutil
import subprocess
import time
from pathlib import Path
from typing import Callable, Optional

import libvirt

log = logging.getLogger("forensicnova.forensics")

# Safety margin for disk pre-check: require 20% headroom above estimated size.
_DISK_SAFETY_FACTOR = 1.2


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def acquire_memory(
    instance_id: str,
    acquisition_id: str,
    work_dir: str,
    libvirt_uri: str = "qemu:///system",
    log_event: Optional[Callable[[str, dict], None]] = None,
) -> Path:
    """Acquire the RAM of a running Nova instance at hypervisor level.

    :param instance_id:    Nova instance UUID (e.g. "a3f2c1d0-1234-...").
    :param acquisition_id: Unique acquisition UUID generated by the caller.
    :param work_dir:       Base working directory from config
                           (default: /var/lib/forensicnova).
    :param libvirt_uri:    libvirt connection URI (default: qemu:///system).
    :param log_event:      Optional CoC callback(event_type, data).

    :returns: Path to the raw dump file on the hypervisor filesystem,
              owned by stack:stack so the rest of the pipeline can read it.
    """
    _emit(log_event, "acquisition_initiated", {
        "instance_id": instance_id,
        "acquisition_id": acquisition_id,
    })

    log.info("connecting to libvirt: %s", libvirt_uri)
    conn = libvirt.open(libvirt_uri)
    if conn is None:
        raise RuntimeError(f"failed to open libvirt connection: {libvirt_uri}")

    try:
        # ------------------------------------------------------------------
        # Resolve Nova UUID → libvirt domain
        # ------------------------------------------------------------------
        log.info("looking up domain for instance %s", instance_id)
        try:
            domain = conn.lookupByUUIDString(instance_id)
        except libvirt.libvirtError as exc:
            raise libvirt.libvirtError(
                f"domain not found for instance_id={instance_id}: {exc}"
            ) from exc

        domain_name = domain.name()
        log.info("domain resolved: %s -> %s", instance_id, domain_name)
        _emit(log_event, "domain_lookup_completed", {
            "instance_id": instance_id,
            "domain_name": domain_name,
        })

        # Verify domain is RUNNING (virsh dump fails on SHUTOFF)
        state, _ = domain.state()
        if state != libvirt.VIR_DOMAIN_RUNNING:
            state_name = _domain_state_name(state)
            raise RuntimeError(
                f"domain {domain_name} is not running (state={state_name}). "
                "RAM acquisition requires an active guest."
            )

        # Pre-check disk space
        max_mem_kib = domain.maxMemory()
        estimated_bytes = max_mem_kib * 1024
        _check_disk_space(work_dir, estimated_bytes)

        # Create per-acquisition staging directory (mode 700)
        acq_dir = Path(work_dir) / "acquisitions" / acquisition_id
        acq_dir.mkdir(parents=True, exist_ok=True)
        acq_dir.chmod(0o700)
        dump_path = acq_dir / "dump.raw"

        log.info(
            "staging dir created: %s (estimated dump size: %.1f MB)",
            acq_dir, estimated_bytes / 1024 / 1024,
        )

        # ------------------------------------------------------------------
        # Dump RAM via libvirt coreDumpWithFormat
        #   Equivalent CLI: virsh dump <domain> <path> --memory-only --format raw
        #   libvirtd writes the file as root:root (QEMU driver runs privileged).
        # ------------------------------------------------------------------
        log.info("virsh dump starting: domain=%s -> %s", domain_name, dump_path)
        _emit(log_event, "virsh_dump_started", {
            "domain_name": domain_name,
            "dump_path": str(dump_path),
            "estimated_bytes": estimated_bytes,
        })

        t_start = time.monotonic()
        domain.coreDumpWithFormat(
            str(dump_path),
            libvirt.VIR_DOMAIN_CORE_DUMP_FORMAT_RAW,
            libvirt.VIR_DUMP_MEMORY_ONLY,
        )
        duration = time.monotonic() - t_start

        actual_bytes = os.stat(str(dump_path)).st_size

        log.info(
            "virsh dump completed: size=%d bytes (%.1f MB), duration=%.1fs",
            actual_bytes, actual_bytes / 1024 / 1024, duration,
        )
        _emit(log_event, "virsh_dump_completed", {
            "domain_name": domain_name,
            "dump_path": str(dump_path),
            "file_size_bytes": actual_bytes,
            "duration_seconds": round(duration, 3),
        })

        # ------------------------------------------------------------------
        # Chown dump to stack:stack so the rest of the pipeline can read it.
        # libvirtd created the file as root:root; we need it owned by the
        # service user that runs hasher, swift uploader, and secure_delete.
        # 'stack' has NOPASSWD sudo in DevStack, so this never blocks.
        # ------------------------------------------------------------------
        service_user = os.environ.get("USER") or "stack"
        log.info("chowning dump to %s:%s", service_user, service_user)
        subprocess.run(
            [
                "sudo", "-n", "chown",
                f"{service_user}:{service_user}", str(dump_path),
            ],
            check=True,
            capture_output=True,
        )
        # Now the file is ours — set permissive-for-us, deny-for-others.
        os.chmod(str(dump_path), 0o600)
        _emit(log_event, "dump_ownership_fixed", {
            "dump_path": str(dump_path),
            "owner": service_user,
            "mode": "0600",
        })

        return dump_path

    finally:
        conn.close()


def secure_delete(path: Path) -> None:
    """Overwrite and unlink a file using shred.

    Called by the pipeline (app/api/v1.py) AFTER Swift upload is confirmed
    via etag verification.  Never called if upload failed — preserves the
    local copy for forensic debugging.
    """
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"secure_delete: file not found: {path}")

    log.info("secure delete: %s", path)
    subprocess.run(
        ["shred", "-u", "-n", "1", str(path)],
        check=True,
        capture_output=True,
    )
    log.info("secure delete completed: %s", path)

    # Remove the now-empty staging directory if it is empty.
    parent = path.parent
    try:
        parent.rmdir()
        log.info("staging dir removed: %s", parent)
    except OSError:
        log.debug("staging dir not empty, left in place: %s", parent)


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------

def _emit(
    log_event: Optional[Callable[[str, dict], None]],
    event_type: str,
    data: dict,
) -> None:
    """Fire the CoC callback if present; always log at DEBUG level."""
    log.debug("coc_event %s: %s", event_type, data)
    if log_event is not None:
        log_event(event_type, data)


def _check_disk_space(work_dir: str, estimated_bytes: int) -> None:
    """Raise OSError if free space in work_dir is below the safety threshold."""
    os.makedirs(work_dir, exist_ok=True)
    stat = os.statvfs(work_dir)
    free_bytes = stat.f_bavail * stat.f_frsize
    required_bytes = int(estimated_bytes * _DISK_SAFETY_FACTOR)
    if free_bytes < required_bytes:
        raise OSError(
            f"insufficient disk space for acquisition: "
            f"free={free_bytes // 1024 // 1024} MB, "
            f"required={required_bytes // 1024 // 1024} MB "
            f"(estimated dump {estimated_bytes // 1024 // 1024} MB "
            f"+ {int((_DISK_SAFETY_FACTOR - 1) * 100)}% margin)"
        )
    log.info(
        "disk pre-check OK: free=%d MB, required=%d MB",
        free_bytes // 1024 // 1024,
        required_bytes // 1024 // 1024,
    )


def _domain_state_name(state: int) -> str:
    """Human-readable libvirt domain state for error messages."""
    _states = {
        libvirt.VIR_DOMAIN_NOSTATE:     "NOSTATE",
        libvirt.VIR_DOMAIN_RUNNING:     "RUNNING",
        libvirt.VIR_DOMAIN_BLOCKED:     "BLOCKED",
        libvirt.VIR_DOMAIN_PAUSED:      "PAUSED",
        libvirt.VIR_DOMAIN_SHUTDOWN:    "SHUTDOWN",
        libvirt.VIR_DOMAIN_SHUTOFF:     "SHUTOFF",
        libvirt.VIR_DOMAIN_CRASHED:     "CRASHED",
        libvirt.VIR_DOMAIN_PMSUSPENDED: "PMSUSPENDED",
    }
    return _states.get(state, f"UNKNOWN({state})")
